version: '3.1'
services:
  db-notification-service:
    image: mongo
    container_name: db-notification-service
    hostname: db-notification-service
    restart: always
    volumes:
      - mongodb_data_notification:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
  notification-service:
    image: diyset/notification-service:master-latest
    hostname: notification-service
    container_name: notification-service
    environment:
      DEBUG: false
      DB_ENGINE: mongodb
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: mbanking_notification
      DB_PORT: 27017
      DB_HOST: db-notification-service
      KAFKA_HOST: kafka1:9094
      KAFKA_PORT: 9092
      PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - dbnotif
      - kafka1
      - zookeeper1
    ports:
      - 9202:8080
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper1
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - 22181:2181

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper1
    ports:
      - 29092:29092
      - 9999:9999
      - 9092:9092
      - 19092:19092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092,KAFKA_DOCKER://kafka1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT,KAFKA_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_JMX_PORT: 9999

volumes:
  mongodb_data_notification:
